version: 0.0.0-{build}

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\Scripts\\pip.exe install cython==0.21 pipenv buildozer"
  # - "%PYTHON%\\Scripts\\pip.exe install --upgrade setuptools"
  - "%PYTHON%\\Scripts\\pipenv.exe install --sequential --dev --skip-lock"
  - "%PYTHON%\\Scripts\\pipenv.exe graph"
  - "%PYTHON%\\Scripts\\pipenv.exe run pyinstaller -D --windowed --name KrappaChat krappachat\\main.py"

build: off

test: off

artifacts:
  - path: dist\*
