version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
  GLEW: glew-2.1.0

install:
  - ps: | # set environment
      $env:PY = $env:PYTHON + "/Scripts"
  - ps: | # install glew
      appveyor DownloadFile $("https://github.com/nigels-com/glew/releases/download/glew-2.1.0/" + $env:GLEW + "-win32.zip")
      7z x $env:GLEW -aos -o"."
      dir $env:GLEW
      move $env:GLEW/bin/glew32.dll $env:systemroot/system32
      move $env:GLEW/lib/glew32.lib $env:PYTHON/Lib
      move $env:GLEW/include/GL/glew.h $env:PYTHON/Include/GL
      move $env:GLEW/include/GL/wglew.h $env:PYTHON/Include/GL
      dir
  - ps: | # python stuff
      $env:PY/pip.exe install cython==0.21 pipenv buildozer
  - ps: | # pipenv stuff
      $env:PY/pipenv.exe install --sequential --dev --skip-lock
  - ps: |
      $env:PY/pipenv.exe graph
  - ps: | # build and pack
      $env:PY/pipenv.exe run pyinstaller -D --windowed --name KrappaChat krappachat/main.py


build: off

test: off

artifacts:
  - path: dist\*
