version: {build}

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
  GLEW: glew-2.1.0-win32.zip

install:
  - ps: | # set environment
      $env:PIP = %PYTHON%\Scripts\pip.exe
      $env:PIPENV = %PYTHON%\Scripts\pipenv.exe
  - ps: | # install glew
      appveyor DownloadFile https://github.com/nigels-com/glew/releases/download/glew-2.1.0/$env:GLEW
      7z x $env:GLEW -aos -o"."
  - ps: | # python stuff
      $env:PIP install cython==0.21 pipenv buildozer
      $env:PIPENV install --sequential --dev --skip-lock
      $env:PIPENV graph
  - ps: | # build and pack
      $env:PIPENV run pyinstaller -D --windowed --name KrappaChat krappachat\main.py


build: off

test: off

artifacts:
  - path: dist\*
