version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      ARCH: "Win32"
    - PYTHON: "C:\\Python36-x64"
      ARCH: "x64"
  GLEW: glew-2.1.0

build:
  verbosity: detailed

install:
   # set environment
  - set PY=%PYTHON%/Scripts
  - %PY%\python.exe -m pip install --upgrade pip
   # python stuff
  - %PY%\pip.exe install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew cython==0.21 pipenv buildozer
   # pipenv stuff
  - %PY%\pipenv.exe install --sequential --dev --skip-lock
  - %PY%\pipenv.exe graph
   # build and pack
  - %PY%\pipenv.exe run pyinstaller -D --windowed --name KrappaChat krappachat/main.py


test: off

artifacts:
  - path: dist\*
