version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      ARCH: "Win32"
    - PYTHON: "C:\\Python36-x64"
      ARCH: "x64"
  GLEW: glew-2.1.0

install:
  - ps: | # set environment
      $env:PY = $env:PYTHON + "/Scripts"
  - ps: |
      $env:PY/pip.exe install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
#  - ps: | # install glew
#      $GLEW_ZIP = $env:GLEW + "-win32.zip"
#      appveyor DownloadFile https://github.com/nigels-com/glew/releases/download/glew-2.1.0/$GLEW_ZIP
#      7z x $GLEW_ZIP -aos -o"."
#      dir $env:GLEW
#      dir $env:GLEW/bin/Release/$env:ARCH
#      dir $env:GLEW/lib/Release/$env:ARCH
#      dir $env:GLEW/include
#      dir $env:PYTHON/Include/GL
#      move $env:GLEW/bin/Release/$env:ARCH/glew32.dll $env:systemroot/system32
#      move $env:GLEW/lib/Release/$env:ARCH/glew32.lib $env:PYTHON/Lib
#      move $env:GLEW/include/GL/glew.h $env:PYTHON/Include/GL
#      move $env:GLEW/include/GL/wglew.h $env:PYTHON/Include/GL
#      dir
  - ps: | # python jstuff
      $env:PY/pip.exe install cython==0.21 pipenv buildozer
  - ps: | # pipenv stuff
      $env:PY/pipenv.exe install --sequential --dev --skip-lock
  - ps: |
      $env:PY/pipenv.exe graph
  - ps: | # build and pack
      $env:PY/pipenv.exe run pyinstaller -D --windowed --name KrappaChat krappachat/main.py


build: off

test: off

artifacts:
  - path: dist\*
