version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
  GLEW: glew-2.1.0-win32.zip

install:
  - ps: | # set environment
      python --version
      $env:Path += ";" + $env:PYTHON + "/Scripts"
      python --version
  - ps: | # install glew
      appveyor DownloadFile https://github.com/nigels-com/glew/releases/download/glew-2.1.0/$env:GLEW
      7z x $env:GLEW -aos -o"."
      move bin/glew32.dll $env:systemroot/system32
      move lib/glew32.lib $env:PYTHON/Lib
      move include/GL/glew.h $env:PYTHON/Include/GL
      move include/GL/wglew.h $env:PYTHON/Include/GL
      dir
  - ps: | # python stuff
      pip.exe install cython==0.21 pipenv buildozer
  - ps: | # pipenv stuff
      pipenv.exe install --sequential --dev --skip-lock
      pipenv.exe graph
  - ps: | # build and pack
      pipenv.exe run pyinstaller -D --windowed --name KrappaChat krappachat/main.py


build: off

test: off

artifacts:
  - path: dist\*
